[toolchain]
anchor_version = "0.31.1"
package_manager = "npm"

[features]
seeds = false
skip-lint = false

[programs.localnet]
pancho_pvp = "52nguesHaBuF4psFr2uybVnW4angLW2ZtsBRSRmdF8k3"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node tests/smoke.mjs"
